spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://myappdb.ctccqqaw0zho.ap-northeast-2.rds.amazonaws.com:3306/myAppDB?serverTimezone=Asia/Seoul
    username: ssy
    password: myappProjectDB0914
#  servlet:
#    multipart:
#      max-file-size: 50MB
#      max-request-size: 50MB
server:
  port: 8080
cloud:
  aws:
    s3:
      bucket: e-myapp-bucket
    region:
      static: us-east-1
    stack:
      auto: false
    credentials:
      access-key: AKIAW3MEFWD6VOIKVRPB
      secret-key: 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
jwt:
  header: Authorization
  # 특정값을 Base64로 인코딩한 값
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  # 토큰 만료 시간
  token-validity-in-seconds: 1800000
client:
  id: "e13b5816e34807e9c3ef76b9652b60a9"
  login-redirect-uri: "http://localhost:3000/login/kakao"
  logout-redirect-uri: "http://localhost:3000/"
file:
  upload-dir: ${IMAGE_UPLOAD_DIR}
iamport:
  apikey: "3345152447410084"
  secretkey: "0l1cSVbjsp6YKeVJ6vwNhM89Daf6LLeQf8nOMhTmhubEb7zs072595tjbck4OvnMevG8n3UOy3z6yt7l"
