server:
  port: 8080
cloud:
  aws:
    s3:
      bucket: e-myapp-bucket
    region:
      static: us-east-1
    stack:
      auto: false
    credentials:
      access-key: AKIAW3MEFWD6VOIKVRPB
      secret-key: 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
jwt:
  header: Authorization
  # 특정값을 Base64로 인코딩한 값
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  # 토큰 만료 시간
  token-validity-in-seconds: 1800000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://myappdb.ctccqqaw0zho.ap-northeast-2.rds.amazonaws.com:3306/myAppDB?serverTimezone=Asia/Seoul
    username: ssy
    password: myappProjectDB0914
    main:
      allow-bean-definition-overriding: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#    hibernate:
#      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  profiles:
    active: prod

file:
  upload-dir: ${IMAGE_UPLOAD_DIR}


