server:
  port: 8080
jwt:
  header: Authorization
  # 특정값을 Base64로 인코딩한 값
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  # 토큰 만료 시간
  token-validity-in-seconds: 1800000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.106.69.213:3306/myAppDb?serverTimezone=Asia/Seoul
    username: dsjeong
    password: jo0411
    main:
      allow-bean-definition-overriding: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  profiles:
    active: prod

file:
  upload-dir: ${IMAGE_UPLOAD_DIR}


