server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.27.104.22:3306/myAppDb?serverTimezone=Asia/Seoul
    username: dsjeong
    password: jo0411
  spring:
    main:
      allow-bean-definition-overriding: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true