version: '3'

services:
  react-app:
    build:
      context: ./path/to/react-app
    ports:
      - "5000:5000"
    networks:
      - app-network

  springboot-app:
    build:
      context: ./path/to/springboot-app
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge